INSTANCE_INFO = {
  't3.nano': {
    'max_price': '0.002',
    'num_core': 2,
    'num_hdd': 1,
  },
  't4g.nano': {
    'max_price': '0.002',
    'num_core': 2,
    'num_hdd': 1,
  },
  't3.micro': {
    'max_price': '0.01',
    'num_core': 2,
    'num_hdd': 1,
  },
  'm1.small': {
    'max_price': '0.24',
    'num_core': 1,
    'num_hdd': 1,
  },
  'm1.medium': {
    'max_price': '0.48',
    'num_core': 1,
    'num_hdd': 1,
  },
  'm1.large': {
    'max_price': '0.96',
    'num_core': 2,
    'num_hdd': 2,       # no good, now sooo good
  },
  'm1.xlarge': {
    'max_price': '0.96',
    'num_core': 4,
    'num_hdd': 4,
    'memory': 14,
  },
  'c1.medium': {
    'max_price': '0.48',
    'num_core': 2,
    'num_hdd': 1,
  },
  'm2.2xlarge': {
    'max_price': '0.98',
    'num_core': 4,
    'num_hdd': 1,
    'memory': 34.2,
  },
  'm2.4xlarge': {
    'max_price': '0.98',
    'num_core': 8,
    'num_hdd': 2,
    'memory': 67,
  },
  'm3.medium': {
    'max_price': '0.452',
    'num_core': 1,
    'num_hdd': 1,
  },
  'm3.large': {
    'max_price': '0.896',
    'num_core': 2,
    'num_hdd': 1,
  },
  'm3.xlarge': {
    'max_price': '0.96',
    'num_core': 4,
    'num_hdd': 2,
  },
  'm3.2xlarge': {
    'max_price': '0.96',
    'num_core': 8,
    'num_hdd': 2,
  },
  'c3.large': {
    'max_price': '1.20',
    'num_core': 2,
    'num_hdd': 2,
  },
  'c3.xlarge': {
    'max_price': '0.96',
    'num_core': 4,
    'num_hdd': 2,
  },
  'c3.2xlarge': {
    'max_price': '0.96',
    'num_core': 8,
    'num_hdd': 2,
    'memory': 14,
  },
  'c3.4xlarge': {
    'max_price': '0.96',
    'num_core': 16,
    'num_hdd': 2,
    'memory': 29,
  },
  'c3.8xlarge': {
    'max_price': '1.92',
    'num_core': 32,
    'num_hdd': 2,
    'memory': 59,
  },
  'c4.8xlarge': {
    'max_price': '1.92',
    'num_core': 32,
    'num_hdd': 0,
    'memory': 59,
  },
  'c6a.32xlarge': {
    'max_price': '4.89',
    'num_core': 128,
    'memory': 256,
    'num_hdd': 1
  },
  'r3.large': {
    'max_price': '0.96',
    'num_core': 2,
    'num_hdd': 1,
  },
  'r3.xlarge': {
    'max_price': '0.96',
    'num_core': 4,
    'num_hdd': 1,
  },
  'r3.2xlarge': {
    'max_price': '0.96',
    'num_core': 8,
    'num_hdd': 1,
  },
  'r3.4xlarge': {
    'max_price': '0.96',
    'num_core': 16,
    'num_hdd': 1,
  },
  'm5d.large': {
    'max_price': '0.96',
    'num_core': 2,
    'memory': 8,
    'num_hdd': 1,
    'nvme': True,
    'nitro_based':  True,
  },
  'm5d.xlarge': {
    'max_price': '0.96',
    'num_core': 4,
    'memory': 16,
    'num_hdd': 1,
    'nvme': True,
    'nitro_based':  True,
  },
  'm5d.2xlarge': {
    'max_price': '0.96',
    'num_core': 8,
    'memory': 32,
    'num_hdd': 1,
    'nvme': True,
    'nitro_based':  True,
  },
  'm5d.4xlarge': {
    'max_price': '0.96',
    'num_core': 16,
    'memory': 63,
    'num_hdd': 2,
    'nvme': True,
    'nitro_based':  True,
  },
  'm5d.8xlarge': {
    'max_price': '1.96',
    'num_core': 32,
    'memory': 128,
    'num_hdd': 2,
    'nvme': True,
    'nitro_based': True,
  },
  'm5d.12xlarge': {
    'max_price': '1.96',
    'num_core': 48,
    'memory': 192,
    'num_hdd': 2,
    'nvme': True,
    'nitro_based': True,
  },
  'c5d.large': {
    'max_price': '0.96',
    'num_core': 2,
    'memory': 4,
    'num_hdd': 1,
    'nvme': True,
    'nitro_based': True,
  },
  'c5d.xlarge': {
    'max_price': '0.96',
    'num_core': 4,
    'memory': 8,
    'num_hdd': 1,
    'nvme': True,
    'nitro_based': True,
  },
  'c5d.2xlarge': {
    'max_price': '0.96',
    'num_core': 8,
    'memory': 16,
    'num_hdd': 1,
    'nvme': True,
    'nitro_based': True,
  },
  'c5d.4xlarge': {
    'max_price': '0.96',
    'num_core': 16,
    'memory': 32,
    'num_hdd': 1,
    'nvme': True,
    'nitro_based': True,
  },
  'c5d.9xlarge': {
    'max_price': '1.20',
    'num_core': 36,
    'memory': 72,
    'num_hdd': 1,
    'nvme': True,
    'nitro_based': True,
  },
  'c5d.18xlarge': {
    'max_price': '1.96',
    'num_core': 72,
    'memory': 144,
    'num_hdd': 2,
    'nvme': True,
    'nitro_based': True,
  },
  'c5d.24xlarge': {
    'max_price': '4.96',
    'num_core': 96,
    'memory': 192,
    'num_hdd': 4,
    'nvme': True,
    'nitro_based': True,
  },
  'i3.2xlarge': {
    'max_price': '1.96',
    'num_core': 8,
    'memory': 61,
    'num_hdd': 1,
    'nvme': True,
  },
  'i3.4xlarge': {
    'max_price': '1.96',
    'num_core': 16,
    'memory': 122,
    'num_hdd': 2,
    'nvme': True,
  },
  'i3.8xlarge': {
    'max_price': '0.96',
    'num_core': 32,
    'memory': 242,
    'num_hdd': 4,   # nvme1n1
    'nvme': True,
  },
  'i3.16xlarge': {
    'max_price': '1.96',
    'num_core': 64,
    'memory': 488,
    'num_hdd': 8,   # nvme1n1
    'nvme': True,
  },
  'i3en.xlarge': {
    'max_price': '0.96',
    'num_core': 4,
    'memory': 32,
    'num_hdd': 1,   # nvme1n1
    'nvme': True,
    'nitro_based': True,
  },
  'i4i.2xlarge': {
      'max_price': '0.96',
      'num_core': 8,
      'memory': 64,
      'num_hdd': 1,
      'nvme': True,
      'nitro_based': True,
  },
  'i4i.4xlarge': {
      'max_price': '0.96',
      'num_core': 16,
      'memory': 128,
      'num_hdd': 1,
      'nvme': True,
      'nitro_based': True,
  },
  'i4i.8xlarge': {
      'max_price': '1.96',
      'num_core': 32,
      'memory': 256,
      'num_hdd': 2,
      'nvme': True,
      'nitro_based': True,
  },
  'i4i.12xlarge': {
      'max_price': '1.96',
      'num_core': 48,
      'memory': 384,
      'num_hdd': 3,
      'nvme': True,
      'nitro_based': True,
  },
  'i4i.16xlarge': {
      'max_price': '2.26',
      'num_core': 64,
      'memory': 512,
      'num_hdd': 4,
      'nvme': True,
      'nitro_based': True,
  },
  'r6id.16xlarge': {
    'max_price': '1.96',
    'num_core': 64,
    'memory': 512,
    'num_hdd': 2,
    'nvme': True,
    'nitro_based': True,
  },
  'm6gd.medium': {
    'max_price': '0.48',
    'num_core': 1,
    'memory': 4,
    'num_hdd': 1,
    'nvme': True,
    'nitro_based': True,
  },
  'c6gd.large': {
    'max_price': '0.48',
    'num_core': 2,
    'memory': 4,
    'num_hdd': 1,
    'nvme': True,
    'nitro_based': True,
  },
  'x1e.16xlarge': {
    'max_price': '4.50',
    'num_core': 64,
    'memory': 1952,
    'num_hdd': 1,
    'nvme': False,
    'nitro_based': False,
  },
}
